### ISSUE TITLE
Detect the version of React rather than hardcode it

### ISSUE THREAD

**Issue by colinharris05** [Gusto/eslint-config-gusto#15]
https://github.com/Gusto/eslint-config-gusto/blob/d62ddcd6fe37695c327a25c833dd7cfc1956585c/index.js#L28

We shouldn't hardcode this value anymore, and [there seems to be a `detect` option now](https://www.npmjs.com/package/eslint-plugin-react#configuration). Gcorp is on latest React and will likely always be ahead of ZP (as it's a smaller project).

I briefly looked through the [React plugin code](https://github.com/yannickcr/eslint-plugin-react) to see how React versions are used, but didn't come up with much.

**Context**
This came up as I ran into some unexpected lint issues today, so I started poking around and found this.

**Comment by wheeler** [comment]
Changed to detect in `9.6.0` with https://github.com/Gusto/eslint-config-gusto/pull/18
